// KnowledgeGraph Component: Interactive D3 force-directed Incident investigation graph.
import { api } from "../api.js";
import { forceGraph } from "../graph.js";

const NODE_COLORS = {
  incident: "#f59e0b",   // Amber
  evidence: "#06b6d4",   // Cyan
  host: "#3b82f6",       // Soft Blue
  hypothesis: "#8b5cf6", // Violet
  root: "#ef4444",       // Critical Red
  action: "#10b981"      // Emerald Green
};

export class KnowledgeGraph {
  constructor(containerId, detailId) {
    this.container = document.querySelector(containerId);
    this.detailPanel = document.querySelector(detailId);
  }

  async render(selectedId, detail) {
    if (!this.container) return;

    if (!selectedId) {
      this.container.innerHTML = `<div class="empty">Please select an incident from the Incident list first.</div>`;
      if (this.detailPanel) this.detailPanel.innerHTML = `Select a node in the graph to view properties.`;
      return;
    }

    if (!detail) {
      this.container.innerHTML = `<div class="empty"><span class="spinner"></span> Querying incident details...</div>`;
      return;
    }

    // Try to get hypotheses generated by the engine
    let engine = null;
    try {
      // Regenerate or load existing hypotheses
      engine = await api(`/incidents/${selectedId}/hypotheses/regenerate`, { method: "POST" });
    } catch (e) {
      console.warn("Could not load hypotheses for graph:", e);
    }

    // Populate legend
    let legendHtml = ``;
    Object.entries(NODE_COLORS).forEach(([type, color]) => {
      legendHtml += `<span><span class="dot" style="background:${color}"></span>${type.charAt(0).toUpperCase() + type.slice(1)}</span>`;
    });
    
    // Create the wrapper
    this.container.innerHTML = `
      <div class="legend" id="kgLegend">${legendHtml}</div>
      <div id="kgSvgHost" style="width:100%; height:460px; position:relative;"></div>
    `;

    const host = document.getElementById("kgSvgHost");
    if (!host) return;

    // Build Nodes & Links
    const nodes = [];
    const links = [];
    const seen = new Set();

    const addNode = (id, label, type, meta, r = 11) => {
      if (!seen.has(id)) {
        seen.add(id);
        nodes.push({
          id,
          label,
          type,
          meta,
          color: NODE_COLORS[type],
          r
        });
      }
    };

    const inc = detail.incident;
    // Primary incident node
    addNode("inc", `INC #${inc.incident_id}`, "incident", `${inc.attack_cat} | Severity: ${inc.severity}`, 18);

    // Impacted host node
    addNode(`host:${inc.node_id}`, inc.node_id, "host", "Primary affected node in telemetry", 13);
    links.push({ source: "inc", target: `host:${inc.node_id}` });

    // Add Evidence nodes
    const evidenceList = detail.evidence || [];
    evidenceList.slice(0, 10).forEach((e, idx) => {
      const evId = `evidence:${idx}`;
      addNode(evId, e.evidence_type, "evidence", `[${e.bucket.toUpperCase()}] ${e.description}`, 11);
      links.push({ source: "inc", target: evId });

      if (e.node_id) {
        addNode(`host:${e.node_id}`, e.node_id, "host", "Evidence source target node", 13);
        links.push({ source: evId, target: `host:${e.node_id}` });
      }
    });

    // Add Hypotheses & Root Causes
    const hypothesesList = (engine && engine.ranked_hypotheses) || detail.hypotheses || [];
    const groundedList = hypothesesList.filter(h => h.grounded).slice(0, 3);
    
    groundedList.forEach((h, idx) => {
      const hypId = `hypothesis:${idx}`;
      addNode(hypId, `Hypothesis #${idx + 1}`, "hypothesis", h.claim, 11);
      links.push({ source: "inc", target: hypId });

      addNode(`root:${h.root_cause_node}`, h.root_cause_node, "root", `Asserted Root Cause: ${h.root_cause_node}`, 14);
      links.push({ source: hypId, target: `root:${h.root_cause_node}` });
    });

    // Add Actions/Remediation (Module 4)
    const remediationSteps = (engine && engine.remediation) || [];
    remediationSteps.slice(0, 4).forEach((step, idx) => {
      const actId = `action:${idx}`;
      addNode(actId, `Mitigation: ${step.step}`, "action", step.rationale, 11);
      // Link to first hypothesis
      if (groundedList.length > 0) {
        links.push({ source: `hypothesis:0`, target: actId });
      } else {
        links.push({ source: "inc", target: actId });
      }
    });

    // Initialize the D3 Force Graph
    try {
      forceGraph(host, nodes, links, {
        height: 440,
        onSelect: (node) => {
          if (this.detailPanel) {
            this.detailPanel.innerHTML = `
              <div style="border-left: 3px solid ${node.color}; padding-left: 10px;">
                <h4 style="text-transform: uppercase; font-size:12px; color:${node.color}; margin-bottom:4px;">
                  ${node.type} node
                </h4>
                <p style="font-weight: 700; font-size: 14.5px; margin-bottom: 6px;">
                  ${node.label}
                </p>
                <p style="color: var(--txt-secondary); font-size:12px;">
                  ${node.meta}
                </p>
              </div>
            `;
            if (window.anime) {
              window.anime({
                targets: this.detailPanel,
                opacity: [0.5, 1],
                translateX: [10, 0],
                duration: 300,
                easing: 'easeOutQuad'
              });
            }
          }
        }
      });
    } catch (err) {
      console.error("Error setting up D3 Force Graph:", err);
      host.innerHTML = `<div class="empty">D3 execution error. Check browser console.</div>`;
    }
  }
}
